### ISSUE TITLE
Windows: build with node@4.2.1

### ISSUE THREAD

**Issue by BergWerkGIS** [naturalatlas/node-gdal#128]
Builds fine with `node@0.12.7`, but with `node@4.2.1` I get:

```
"c:\mb\windows-builds-64\packages\node-gdal\build\binding.sln" (default target) (1) ->
"c:\mb\windows-builds-64\packages\node-gdal\build\action_after_build.vcxproj.metaproj" (default target) (2) ->
"c:\mb\windows-builds-64\packages\node-gdal\build\gdal.vcxproj.metaproj" (default target) (3) ->
"c:\mb\windows-builds-64\packages\node-gdal\build\deps\libgeos\libgeos.vcxproj" (default target) (7) ->
(ClCompile target) ->
  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\typeinfo(38): error C2504: 'exception': base class undefined (co mpiling source file ..\..\..\deps\libgeos\geos\src\geom\util\CoordinateOperation.cpp) [c:\mb\windows-builds-64\packages\node-gdal \build\deps\libgeos\libgeos.vcxproj]
  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\typeinfo(42): error C2614: 'std::bad_cast': illegal member initi alization: 'exception' is not a base or member (compiling source file ..\..\..\deps\libgeos\geos\src\geom\util\CoordinateOperatio n.cpp) [c:\mb\windows-builds-64\packages\node-gdal\build\deps\libgeos\libgeos.vcxproj]
  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\typeinfo(59): error C2504: 'exception': base class undefined (co mpiling source file ..\..\..\deps\libgeos\geos\src\geom\util\CoordinateOperation.cpp) [c:\mb\windows-builds-64\packages\node-gdal \build\deps\libgeos\libgeos.vcxproj]
  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\typeinfo(63): error C2614: 'std::bad_typeid': illegal member ini tialization: 'exception' is not a base or member (compiling source file ..\..\..\deps\libgeos\geos\src\geom\util\CoordinateOperat ion.cpp) [c:\mb\windows-builds-64\packages\node-gdal\build\deps\libgeos\libgeos.vcxproj]
```

**Comment by BergWerkGIS** [comment]
Oh, seems to be a bug in VS2015:

*"It's been fixed and will be available in VS 2015 Update 2."*
https://connect.microsoft.com/VisualStudio/feedback/details/1600701/type-info-does-not-compile-with-has-exceptions-0

Will investigate, if there is a workaround till `VS2015 Update 2` is available.

**Comment by BergWerkGIS** [comment]
Got local builds working with https://github.com/naturalatlas/node-gdal/commit/4d3b5ca2b0e64e7202b99038f4440fbe007d600f

AppVeyor still doing his thing:
https://ci.appveyor.com/project/brianreavis/node-gdal/build/575

Seems there is no `node@3.3.1` on AppVeyor.

**Comment by weagle08** [comment]
Follow this issue: [https://github.com/naturalatlas/node-gdal/issues/119](#119)
The underlying cause is the update to the latest v8 engine. The issue is currently awaiting some updates to the NaN project for Nodejs v4.x and once they are in node-gdal will hopefully be updated.

**Comment by brianreavis** [comment]
@weagle08 The NAN upgrade is complete as of [0.7.2](https://github.com/naturalatlas/node-gdal/releases/tag/v0.7.2). Windows builds take some additional sorcery, which is what @BergWerkGIS is handling with this issue.

**Comment by weagle08** [comment]
Oh, ok.. The exception he referenced was the first one i spent time fixing, and then several others after that before I realized the #119 issue. Just didn't want him spending all the time I had. Thanks for the update!

**Comment by BergWerkGIS** [comment]
> The exception he referenced was the first one i spent time fixing, and then several others after that before I realized the #119 issue.

@weagle08 interesting, after https://github.com/naturalatlas/node-gdal/commit/4d3b5ca2b0e64e7202b99038f4440fbe007d600f there were no other exceptions for me.

All other commits are about making the build faster on AppVeyor to not run into the build time limit.

AppVeyor, is also green for `node@4.2.1` for the branch (https://github.com/naturalatlas/node-gdal/tree/win-node-4.2.1) I'm currently working on:
e.g.: https://ci.appveyor.com/project/brianreavis/node-gdal/build/581

After some cleanup I will issue a PR to get the changes merged.

**Comment by BergWerkGIS** [comment]
@weagle08 forgot: `node-pre-gyp` has to updated to latest, otherwise I doesn't know about `4.2.1`.

**Comment by BergWerkGIS** [comment]
PR: https://github.com/naturalatlas/node-gdal/pull/129

**Comment by brianreavis** [comment]
https://github.com/naturalatlas/node-gdal/releases/tag/v0.8.0
